export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

export const LOGOUT = 'USERS_LOGOUT'

export const SIGNUP_SUCCESS = 'USERS_SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'USERS_SIGNUP_FAILURE'

export const GETALL_REQUEST = 'USERS_GETALL_REQUEST'
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS'
export const GETALL_FAILURE = 'USERS_GETALL_FAILURE'

export const RESET_REQUESTED = 'RESET_REQUESTED'
export const PASSWORD_RESET = 'PASSWORD_RESET'

export const GET_USER = 'GET_USER'

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_TOAST = 'SET_TOAST'
export const RESET_TOAST = 'RESET_TOAST'
export const SET_ERROR = 'SET_ERROR'
export const RESET_ERROR = 'RESET_ERROR'

export const CREATE_KITBAG_KIT = 'CREATE_KITBAG_KIT';
export const FETCH_KITBAG_KITS = 'FETCH_KITBAG_KITS';
export const FETCH_KITBAG_KIT = 'FETCH_KITBAG_KIT';
export const EDIT_KITBAG_KIT = 'EDIT_KITBAG_KIT';
export const DELETE_KITBAG_KIT = 'DELETE_KITBAG_KIT';
export const API_KITBAG_ERROR = 'API_KITBAG_ERROR';

export const CREATE_KITBAG_WANTED = 'CREATE_KITBAG_WANTED';
export const FETCH_KITBAG_WANTEDS = 'FETCH_KITBAG_WANTEDS';
export const FETCH_KITBAG_WANTED = 'FETCH_KITBAG_WANTED';
export const EDIT_KITBAG_WANTED = 'EDIT_KITBAG_WANTED';
export const DELETE_KITBAG_WANTED = 'DELETE_KITBAG_WANTED';

export const CREATE_KITBAG_FORSALE = 'CREATE_KITBAG_FORSALE';
export const FETCH_KITBAG_FORSALES = 'FETCH_KITBAG_FORSALES';
export const FETCH_KITBAG_FORSALE = 'FETCH_KITBAG_FORSALE';
export const EDIT_KITBAG_FORSALE = 'EDIT_KITBAG_FORSALE';
export const DELETE_KITBAG_FORSALE = 'DELETE_KITBAG_FORSALE';

export const ADD_IMAGE = 'ADD_IMAGE';
export const CLEAR_NEW_IMAGES = 'CLEAR_NEW_IMAGES';