export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SIGNUP_SUCCESS = "USERS_SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "USERS_SIGNUP_FAILURE";

export const GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const GETALL_FAILURE = "USERS_GETALL_FAILURE";

export const RESET_REQUESTED = "RESET_REQUESTED";
export const PASSWORD_RESET = "PASSWORD_RESET";

export const GET_USER = "GET_USER";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const FETCH_SUBSCRIPTION_PACKAGE = "FETCH_SUBSCRIPTION_PACKAGE";

export const RESET_TOAST = "RESET_TOAST";
export const SHOWN_TOAST = "SHOWN_TOAST";
export const FLAG_TOAST = "FLAG_TOAST";
export const SET_TOAST = "SET_TOAST";
export const SET_ERROR = "SET_ERROR";

export const CREATE_KITBAG_KIT = "CREATE_KITBAG_KIT";
export const FETCH_KITBAG_KITS = "FETCH_KITBAG_KITS";
export const FETCH_KITBAG_KIT = "FETCH_KITBAG_KIT";
export const EDIT_KITBAG_KIT = "EDIT_KITBAG_KIT";
export const DELETE_KITBAG_KIT = "DELETE_KITBAG_KIT";
export const API_KITBAG_ERROR = "API_KITBAG_ERROR";

export const CREATE_KITBAG_TRADE = "CREATE_KITBAG_TRADE";
export const FETCH_KITBAG_TRADES = "FETCH_KITBAG_TRADES";
export const FETCH_KITBAG_TRADE = "FETCH_KITBAG_TRADE";
export const EDIT_KITBAG_TRADE = "EDIT_KITBAG_TRADE";
export const DELETE_KITBAG_TRADE = "DELETE_KITBAG_TRADE";

export const CREATE_KITBAG_WANTED = "CREATE_KITBAG_WANTED";
export const FETCH_KITBAG_WANTEDS = "FETCH_KITBAG_WANTEDS";
export const FETCH_KITBAG_WANTED = "FETCH_KITBAG_WANTED";
export const EDIT_KITBAG_WANTED = "EDIT_KITBAG_WANTED";
export const DELETE_KITBAG_WANTED = "DELETE_KITBAG_WANTED";

export const CREATE_KITBAG_STOLEN = "CREATE_KITBAG_STOLEN";
export const FETCH_KITBAG_STOLENS = "FETCH_KITBAG_STOLENS";
export const FETCH_KITBAG_STOLEN = "FETCH_KITBAG_STOLEN";
export const EDIT_KITBAG_STOLEN = "EDIT_KITBAG_STOLEN";
export const DELETE_KITBAG_STOLEN = "DELETE_KITBAG_STOLEN";

export const ADD_IMAGE = "ADD_IMAGE";
export const CLEAR_NEW_IMAGES = "CLEAR_NEW_IMAGES";

export const API_MARKET_ERROR = "API_MARKET_ERROR";
export const FETCH_MARKET_TRADES = "FETCH_MARKET_TRADES";
export const FETCH_MARKET_TRADE = "FETCH_MARKET_TRADE";

export const FETCH_MARKET_WANTEDS = "FETCH_MARKET_WANTEDS";
export const FETCH_MARKET_WANTED = "FETCH_MARKET_WANTED";

export const FETCH_MARKET_STOLENS = "FETCH_MARKET_STOLENS";
export const FETCH_MARKET_STOLEN = "FETCH_MARKET_STOLEN";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const FETCH_GROUP = "FETCH_GROUP";
export const FETCH_GROUP_MEMBERS = "FETCH_GROUP_MEMBERS";
export const CREATE_GROUP = "CREATE_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const EDIT_GROUP_STATUS = "EDIT_GROUP_STATUS";
export const EDIT_GROUP_MEMBER_STATE = "EDIT_GROUP_MEMBER_STATE";
